package jinke.com.parquetOperate;


//import com.jinke.parqueteventservice.vo.DouYinFansVo;
import jinke.com.ov.DouYinFansVo;
import lombok.extern.slf4j.Slf4j;
import org.apache.commons.lang.StringUtils;
import org.apache.parquet.example.data.Group;
import org.apache.parquet.example.data.GroupFactory;
import org.apache.parquet.example.data.simple.SimpleGroupFactory;
import org.apache.parquet.schema.MessageType;
import org.apache.parquet.schema.OriginalType;
import org.apache.parquet.schema.PrimitiveType;
import org.apache.parquet.schema.Types;


/**
 * Created by tanghanzhuang on 2018/7/30
 */
@Slf4j
public class DouYinFansParquetHandler {
    public static MessageType BuildMessageType() {
        MessageType messageType = Types.buildMessage()
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("accept_private_policy")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("account_region")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("activity_digg_count")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("activity_use_music_count")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("apple_account")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("authority_status")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("avatar_larger_url")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("avatar_medium_url")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("avatar_thumb_url")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("bind_phone")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("birthday")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("age_grades")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("commerce_user_level")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("constellation")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("custom_verify")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("dongtai_count")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("enterprise_verify_reason")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("favoriting_count")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("fb_expire_time")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("follow_status")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("follower_count")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("following_id")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("following_count")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("gender")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("google_account")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("has_activity_medal")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("has_email")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("has_facebook_token")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("has_orders")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("has_twitter_token")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("has_youtube_token")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("hide_location")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("hide_search")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("ins_id")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("is_ad_fake")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("is_binded_weibo")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("is_block")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("is_discipline_member")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("is_flowcard_member")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("is_gov_media_vip")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("is_phone_binded")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("is_verified")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("live_agreement")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("live_verify")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("location")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("location_province")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("location_city")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("location_citylevel")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("location_east_longitude")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("location_northern_latitude")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("login_platform")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("mplatform_followers_count")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("need_recommend")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("neiguang_shield")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("nickname")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("original_music_digg_count")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("original_music_count")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("original_music_used_count")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("prevent_download")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("realname_verify_status")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("region")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("room_id")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("school_name")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("school_poi_id")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("school_type")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("secret")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("share_info_bool_persist")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("share_info_desc")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("share_info_image_url")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("share_info_qrcode_url")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("share_info_title")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("share_info_url")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("share_info_weibo_desc")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("shield_comment_notice")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("shield_digg_notice")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("shield_follow_notice")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("short_id")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("show_image_bubble")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("signature")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("special_lock")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("star_use_new_download")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("story_count")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("story_open")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("sync_to_toutiao")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("tenant_id")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("total_favorited")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("tw_expire_time")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("twitter_id")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("twitter_name")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("uid")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("unique_id")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("unique_id_modify_time")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("user_canceled")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("verify_info")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("video_icon_url")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("weibo_name")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("weibo_schema")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("weibo_url")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("weibo_verify")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("with_commerce_entry")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("with_dou_entry")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("with_douplus_entry")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("with_fusion_shop_entry")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("with_new_goods")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("with_shop_entry")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("youtube_channel_id")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("youtube_channel_title")
                .optional(PrimitiveType.PrimitiveTypeName.BINARY).as(OriginalType.UTF8).named("youtube_expire_time")
                .named("DouYinFans");
        return messageType;
    }

    public static Group getGroup(MessageType messageType, DouYinFansVo fans) {
        GroupFactory factory = new SimpleGroupFactory(messageType);
        Group group = factory.newGroup()
                .append("accept_private_policy", StringUtils.isBlank(fans.getAcceptPrivatePolicy()) ? "" : fans.getAcceptPrivatePolicy().trim())
                .append("account_region", StringUtils.isBlank(fans.getAccountRegion()) ? "" : fans.getAccountRegion().trim())
                .append("activity_digg_count", StringUtils.isBlank(fans.getActivityDiggCount()) ? "" : fans.getActivityDiggCount().trim())
                .append("activity_use_music_count", StringUtils.isBlank(fans.getActivityUseMusicCount()) ? "" : fans.getActivityUseMusicCount().trim())
                .append("apple_account", StringUtils.isBlank(fans.getAppleAccount()) ? "" : fans.getAppleAccount().trim())
                .append("authority_status", StringUtils.isBlank(fans.getAuthorityStatus()) ? "" : fans.getAuthorityStatus().trim())
                .append("avatar_larger_url", StringUtils.isBlank(fans.getAvatarLargerUrl()) ? "" : fans.getAvatarLargerUrl().trim())
                .append("avatar_medium_url", StringUtils.isBlank(fans.getAvatarMediumUrl()) ? "" : fans.getAvatarMediumUrl().trim())
                .append("avatar_thumb_url", StringUtils.isBlank(fans.getAvatarThumbUrl()) ? "" : fans.getAvatarThumbUrl().trim())
                .append("bind_phone", StringUtils.isBlank(fans.getBindPhone()) ? "" : fans.getBindPhone().trim())
                .append("birthday", StringUtils.isBlank(fans.getBirthday()) ? "" : fans.getBirthday().trim())
                .append("age_grades", StringUtils.isBlank(fans.getAgeGrades()) ? "0" : fans.getAgeGrades().trim())
                .append("commerce_user_level", StringUtils.isBlank(fans.getCommerceUserLevel()) ? "" : fans.getCommerceUserLevel().trim())
                .append("constellation", StringUtils.isBlank(fans.getConstellation()) ? "" : fans.getConstellation().trim())
                .append("custom_verify", StringUtils.isBlank(fans.getCustomVerify()) ? "" : fans.getCustomVerify().trim())
                .append("dongtai_count", StringUtils.isBlank(fans.getDongtaiCount()) ? "" : fans.getDongtaiCount().trim())
                .append("enterprise_verify_reason", StringUtils.isBlank(fans.getEnterpriseVerifyReason()) ? "" : fans.getEnterpriseVerifyReason().trim())
                .append("favoriting_count", StringUtils.isBlank(fans.getFavoritingCount()) ? "" : fans.getFavoritingCount().trim())
                .append("fb_expire_time", StringUtils.isBlank(fans.getFbExpireTime()) ? "" : fans.getFbExpireTime().trim())
                .append("follow_status", StringUtils.isBlank(fans.getFollowStatus()) ? "" : fans.getFollowStatus().trim())
                .append("follower_count", StringUtils.isBlank(fans.getFollowerCount()) ? "" : fans.getFollowerCount().trim())
                .append("following_id", StringUtils.isBlank(fans.getFollowingId()) ? "" : fans.getFollowingId().trim())
                .append("following_count", StringUtils.isBlank(fans.getFollowingCount()) ? "" : fans.getFollowingCount().trim())
                .append("gender", StringUtils.isBlank(fans.getGender()) ? "" : fans.getGender().trim())
                .append("google_account", StringUtils.isBlank(fans.getGoogleAccount()) ? "" : fans.getGoogleAccount().trim())
                .append("has_activity_medal", StringUtils.isBlank(fans.getHasActivityMedal()) ? "" : fans.getHasActivityMedal().trim())
                .append("has_email", StringUtils.isBlank(fans.getHasEmail()) ? "" : fans.getHasEmail().trim())
                .append("has_facebook_token", StringUtils.isBlank(fans.getHasFacebookToken()) ? "" : fans.getHasFacebookToken().trim())
                .append("has_orders", StringUtils.isBlank(fans.getHasOrders()) ? "" : fans.getHasOrders().trim())
                .append("has_twitter_token", StringUtils.isBlank(fans.getHasTwitterToken()) ? "" : fans.getHasTwitterToken().trim())
                .append("has_youtube_token", StringUtils.isBlank(fans.getHasYoutubeToken()) ? "" : fans.getHasYoutubeToken().trim())
                .append("hide_location", StringUtils.isBlank(fans.getHideLocation()) ? "" : fans.getHideLocation().trim())
                .append("hide_search", StringUtils.isBlank(fans.getHideSearch()) ? "" : fans.getHideSearch().trim())
                .append("ins_id", StringUtils.isBlank(fans.getInsId()) ? "" : fans.getInsId().trim())
                .append("is_ad_fake", StringUtils.isBlank(fans.getIsAdFake()) ? "" : fans.getIsAdFake().trim())
                .append("is_binded_weibo", StringUtils.isBlank(fans.getIsBindedWeibo()) ? "" : fans.getIsBindedWeibo().trim())
                .append("is_block", StringUtils.isBlank(fans.getIsBlock()) ? "" : fans.getIsBlock().trim())
                .append("is_discipline_member", StringUtils.isBlank(fans.getIsDisciplineMember()) ? "" : fans.getIsDisciplineMember().trim())
                .append("is_flowcard_member", StringUtils.isBlank(fans.getIsFlowcardMember()) ? "" : fans.getIsFlowcardMember().trim())
                .append("is_gov_media_vip", StringUtils.isBlank(fans.getIsGovMediaVip()) ? "" : fans.getIsGovMediaVip().trim())
                .append("is_phone_binded", StringUtils.isBlank(fans.getIsPhoneBinded()) ? "" : fans.getIsPhoneBinded().trim())
                .append("is_verified", StringUtils.isBlank(fans.getIsVerified()) ? "" : fans.getIsVerified().trim())
                .append("live_agreement", StringUtils.isBlank(fans.getLiveAgreement()) ? "" : fans.getLiveAgreement().trim())
                .append("live_verify", StringUtils.isBlank(fans.getLiveVerify()) ? "" : fans.getLiveVerify().trim())
                .append("location", StringUtils.isBlank(fans.getLocation()) ? "" : fans.getLocation().trim())
                .append("location_province", StringUtils.isBlank(fans.getLocationProvince()) ? "" : fans.getLocationProvince().trim())
                .append("location_city", StringUtils.isBlank(fans.getLocationCity()) ? "" : fans.getLocationCity().trim())
                .append("location_citylevel", StringUtils.isBlank(fans.getLocationCitylevel()) ? "" : fans.getLocationCitylevel().trim())
                .append("location_east_longitude", StringUtils.isBlank(fans.getLocationEastLongitude()) ? "" : fans.getLocationEastLongitude().trim())
                .append("location_northern_latitude", StringUtils.isBlank(fans.getLocationNorthernLatitude()) ? "" : fans.getLocationNorthernLatitude().trim())
                .append("login_platform", StringUtils.isBlank(fans.getLoginPlatform()) ? "" : fans.getLoginPlatform().trim())
                .append("mplatform_followers_count", StringUtils.isBlank(fans.getMplatformFollowersCount()) ? "" : fans.getMplatformFollowersCount().trim())
                .append("need_recommend", StringUtils.isBlank(fans.getNeedRecommend()) ? "" : fans.getNeedRecommend().trim())
                .append("neiguang_shield", StringUtils.isBlank(fans.getNeiguangShield()) ? "" : fans.getNeiguangShield().trim())
                .append("nickname", StringUtils.isBlank(fans.getNickname()) ? "" : fans.getNickname().trim())
                .append("original_music_digg_count", StringUtils.isBlank(fans.getOriginalMusicDiggCount()) ? "" : fans.getOriginalMusicDiggCount().trim())
                .append("original_music_count", StringUtils.isBlank(fans.getOriginalMusicCount()) ? "" : fans.getOriginalMusicCount().trim())
                .append("original_music_used_count", StringUtils.isBlank(fans.getOriginalMusicUsedCount()) ? "" : fans.getOriginalMusicUsedCount().trim())
                .append("prevent_download", StringUtils.isBlank(fans.getPreventDownload()) ? "" : fans.getPreventDownload().trim())
                .append("realname_verify_status", StringUtils.isBlank(fans.getRealnameVerifyStatus()) ? "" : fans.getRealnameVerifyStatus().trim())
                .append("region", StringUtils.isBlank(fans.getRegion()) ? "" : fans.getRegion().trim())
                .append("room_id", StringUtils.isBlank(fans.getRoomId()) ? "" : fans.getRoomId().trim())
                .append("school_name", StringUtils.isBlank(fans.getSchoolName()) ? "" : fans.getSchoolName().trim())
                .append("school_poi_id", StringUtils.isBlank(fans.getSchoolPoiId()) ? "" : fans.getSchoolPoiId().trim())
                .append("school_type", StringUtils.isBlank(fans.getSchoolType()) ? "" : fans.getSchoolType().trim())
                .append("secret", StringUtils.isBlank(fans.getSecret()) ? "" : fans.getSecret().trim())
                .append("share_info_bool_persist", StringUtils.isBlank(fans.getShareInfoBoolPersist()) ? "" : fans.getShareInfoBoolPersist().trim())
                .append("share_info_desc", StringUtils.isBlank(fans.getShareInfoDesc()) ? "" : fans.getShareInfoDesc().trim())
                .append("share_info_image_url", StringUtils.isBlank(fans.getShareInfoImageUrl()) ? "" : fans.getShareInfoImageUrl().trim())
                .append("share_info_qrcode_url", StringUtils.isBlank(fans.getShareInfoQrcodeUrl()) ? "" : fans.getShareInfoQrcodeUrl().trim())
                .append("share_info_title", StringUtils.isBlank(fans.getShareInfoTitle()) ? "" : fans.getShareInfoTitle().trim())
                .append("share_info_url", StringUtils.isBlank(fans.getShareInfoUrl()) ? "" : fans.getShareInfoUrl().trim())
                .append("share_info_weibo_desc", StringUtils.isBlank(fans.getShareInfoWeiboDesc()) ? "" : fans.getShareInfoWeiboDesc().trim())
                .append("shield_comment_notice", StringUtils.isBlank(fans.getShieldCommentNotice()) ? "" : fans.getShieldCommentNotice().trim())
                .append("shield_digg_notice", StringUtils.isBlank(fans.getShieldDiggNotice()) ? "" : fans.getShieldDiggNotice().trim())
                .append("shield_follow_notice", StringUtils.isBlank(fans.getShieldFollowNotice()) ? "" : fans.getShieldFollowNotice().trim())
                .append("short_id", StringUtils.isBlank(fans.getShortId()) ? "" : fans.getShortId().trim())
                .append("signature", StringUtils.isBlank(fans.getSignature()) ? "" : fans.getSignature().trim())
                .append("special_lock", StringUtils.isBlank(fans.getSpecialLock()) ? "" : fans.getSpecialLock().trim())
                .append("star_use_new_download", StringUtils.isBlank(fans.getStarUseNewDownload()) ? "" : fans.getStarUseNewDownload().trim())
                .append("story_count", StringUtils.isBlank(fans.getStoryCount()) ? "" : fans.getStoryCount().trim())
                .append("story_open", StringUtils.isBlank(fans.getStoryOpen()) ? "" : fans.getStoryOpen().trim())
                .append("sync_to_toutiao", StringUtils.isBlank(fans.getSyncToToutiao()) ? "" : fans.getSyncToToutiao().trim())
                .append("tenant_id", StringUtils.isBlank(fans.getTenantId()) ? "" : fans.getTenantId().trim())
                .append("total_favorited", StringUtils.isBlank(fans.getTotalFavorited()) ? "" : fans.getTotalFavorited().trim())
                .append("tw_expire_time", StringUtils.isBlank(fans.getTwExpireTime()) ? "" : fans.getTwExpireTime().trim())
                .append("twitter_id", StringUtils.isBlank(fans.getTwitterId()) ? "" : fans.getTwitterId().trim())
                .append("twitter_name", StringUtils.isBlank(fans.getTwitterName()) ? "" : fans.getTwitterName().trim())
                .append("uid", StringUtils.isBlank(fans.getUid()) ? "" : fans.getUid().trim())
                .append("unique_id", StringUtils.isBlank(fans.getUniqueId()) ? "" : fans.getUniqueId().trim())
                .append("unique_id_modify_time", StringUtils.isBlank(fans.getUniqueIdModifyTime()) ? "" : fans.getUniqueIdModifyTime().trim())
                .append("user_canceled", StringUtils.isBlank(fans.getUserCanceled()) ? "" : fans.getUserCanceled().trim())
                .append("verify_info", StringUtils.isBlank(fans.getVerifyInfo()) ? "" : fans.getVerifyInfo().trim())
                .append("video_icon_url", StringUtils.isBlank(fans.getVideoIconUrl()) ? "" : fans.getVideoIconUrl().trim())
                .append("weibo_name", StringUtils.isBlank(fans.getWeiboName()) ? "" : fans.getWeiboName().trim())
                .append("weibo_schema", StringUtils.isBlank(fans.getWeiboSchema()) ? "" : fans.getWeiboSchema().trim())
                .append("weibo_url", StringUtils.isBlank(fans.getWeiboUrl()) ? "" : fans.getWeiboUrl().trim())
                .append("weibo_verify", StringUtils.isBlank(fans.getWeiboVerify()) ? "" : fans.getWeiboVerify().trim())
                .append("with_commerce_entry", StringUtils.isBlank(fans.getWithCommerceEntry()) ? "" : fans.getWithCommerceEntry().trim())
                .append("with_dou_entry", StringUtils.isBlank(fans.getWithDouEntry()) ? "" : fans.getWithDouEntry().trim())
                .append("with_douplus_entry", StringUtils.isBlank(fans.getWithDouplusEntry()) ? "" : fans.getWithDouplusEntry().trim())
                .append("with_fusion_shop_entry", StringUtils.isBlank(fans.getWithFusionShopEntry()) ? "" : fans.getWithFusionShopEntry().trim())
                .append("with_new_goods", StringUtils.isBlank(fans.getWithNewGoods()) ? "" : fans.getWithNewGoods().trim())
                .append("with_shop_entry", StringUtils.isBlank(fans.getWithShopEntry()) ? "" : fans.getWithShopEntry().trim())
                .append("youtube_channel_id", StringUtils.isBlank(fans.getYoutubeChannelId()) ? "" : fans.getYoutubeChannelId().trim())
                .append("youtube_channel_title", StringUtils.isBlank(fans.getYoutubeChannelTitle()) ? "" : fans.getYoutubeChannelTitle().trim())
                .append("youtube_expire_time", StringUtils.isBlank(fans.getYoutubeExpireTime()) ? "" : fans.getYoutubeExpireTime().trim());
        return group;

    }
}

